### ISSUE TITLE
Failed to load pretrained model

### ISSUE THREAD

**Issue by hsmidt** [WSU-SEAL/ToxiCR#1]
Hello, 

thank you for making this tool public. We're trying to use it to analyze some GitHub pull requests, but we're struggling with loading the pre-trained model. We were able to use the pre-trained RF model, but are noticing problems with the BERT algorithm. We've downloaded the models from your GDrive, unzipped them, and then placed them in the `/pre-trained` directory.

This is the output we receive when running the test program from your repo.
```
BERT model selected           : https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3
Preprocess model auto-selected: https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3
2022-11-05 01:51:15.707657: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Unknown decay: WarmUp. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Unable to load pretrained model../Users/xxx/project/code/ToxiCR/./pre-trained/model-BERT-bert-profane-False-keyword-True-split-False.h5
```

Platform: macOS Monterey 12.5 , Ubuntu 20.04
Python version: 3.8 (using virtualenv and pip)

Thank you for any insights you may have.

**Comment by jaydebsarker** [comment]
If you are unable to load the bert pretrain model, please follow the procedure.
1. Retrain the model with the dataset again. If you do not use '--embed bert', it will not save the model name properly though it selects the bert embedding. The error occurs due to naming error of the saved model. 
For retraining the model with bert, use this: python ToxiCR.py --algo BERT --embed bert --keyword --mode pretrain

(here, bert model achieves the best performance with keyword preprocessing true. for that reason, we need to provide this argument here)

2. After training, validation, and testing, the model will be saved as this name 'model-BERT-bert-profane-False-keyword-True-split-False.h5' on pre-trained directory. 

(From ToxiCRTest.py file, it calls the best combination of bert classifier "toxicClassifier=ToxiCR(ALGO="BERT",count_profanity=False, remove_keywords=False, split_identifier=False,embedding="bert", load_pretrained=True)"
)
3. Then you can run ToxiCRTest.py .

**Comment by hsmidt** [comment]
Hello @jaydebsarker , thanks so much for your response and instructions. Do you have any reference for expected training duration with BERT on your system?

**Comment by jaydebsarker** [comment]
@hsmidt , we used 24GB Titan RTX GPU. It took approximately 5 hours for 10-fold cross-validation. The program default setting is repeat==2 (it means 2 times 10 fold cross-validation). You can make it --repeat 1 in the argument.

**Comment by hsmidt** [comment]
Thank you @jaydebsarker . We were able to train it per your instructions.
